version: "2"
run:
  tests: true
  build-tags:
    - integration
formatters:
  enable:
    - gci
    - goimports
    - gofmt
    - gofumpt
    - golines
linters:
  default: all
  disable:
    - contextcheck # too many false-positive
    - cyclop # duplicate of gocyclo
    - depguard # import restrictions
    - dupl # Too strict
    - exhaustruct # Not relevant
    - gochecknoglobals
    - gochecknoinits
    - gocognit # Too strict
    - gocyclo
    - gosec # Too strict
    - ireturn # Not relevant
    - lll # Not relevant
    - maintidx # kind of duplicate of gocyclo
    - nestif # Too many false-positive.
    - paralleltest # Not relevant
    - wrapcheck # Too strict
    - wsl # Deprecated

  settings:
    funlen:
      lines: -1
      statements: 120
    misspell:
      locale: US
    gocritic:
      disabled-checks:
        - dupSubExpr
      enabled-checks:
        - ruleguard
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 2
    revive:
      rules:
        # Enforce consistent receiver names
        - name: receiver-naming
          severity: warning
          disabled: false
        # Enforce consistent error variable naming
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - ["err", "Err"] # Allow 'err' and descriptive names ending in 'Err'
            - []
        # Enforce context as first parameter
        - name: context-as-argument
          severity: warning
          disabled: false
          arguments:
            - allowTypesBefore: "*testing.T,*testing.B"
        # Enforce comment formatting
        - name: exported
          severity: warning
          disabled: false
        # Enforce consistent package comments
        - name: package-comments
          severity: warning
          disabled: false
        # Enforce error return as last value
        - name: error-return
          severity: warning
          disabled: false
        # Enforce error strings not capitalized
        - name: error-strings
          severity: warning
          disabled: false
        # Enforce consistent error naming
        - name: error-naming
          severity: warning
          disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
