on:
    pull_request:
        branches: ["*"]
        tags-ignore:
            - "release-please--*" # Exclude tags containing "staging"

name: test build

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.head_ref }}

            - uses: actions/setup-go@v5
              with:
                  go-version: "^1.23.6"

            - name: Install dependencies
              run: go get .

            - name: Ensure go.mod is up to date
              run: go mod tidy

            - name: Check code formatting
              run: |
                  fmt_out=$(go fmt ./...)
                  if [ -n "$fmt_out" ]; then
                    echo "The following files are not formatted:"
                    echo "$fmt_out"
                    exit 1
                  fi

            - name: Run vet
              run: go vet ./...

            - name: Run test
              run: go test ./...
