on:
    pull_request:
        branches: ["*"]
        tags-ignore:
            - "release-please--*" # Exclude tags containing "staging"

name: test build

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.head_ref }}

            - uses: actions/setup-go@v5
              with:
                  go-version: "^1.23.6"

            - name: Make sure build does not error out
              run: |
                  env GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/y3owk1n/nvs/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./build/nvs-darwin-arm64 ./main.go
                  env GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/y3owk1n/nvs/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./build/nvs-darwin-amd64 ./main.go
                  env GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/y3owk1n/nvs/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./build/nvs-linux-amd64 ./main.go
                  env GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/y3owk1n/nvs/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./build/nvs-windows-amd64.exe ./main.go
